Models/FaultLog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MSV_LP.Models
{
    public class FaultLog
    {
        [Key]
        public int ID { get; set; }
        public string Locomotive { get; set; }

        [DataType(DataType.Date)]
        public DateTime DownloadDate { get; set; }
        
        [DataType(DataType.Time)]
        public DateTime DownloadTime { get; set; }
        
        public float Odometr { get; set; }
    }
}

Pages/FaultLogs/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.FaultLogs
{
    public class CreateModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public CreateModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public FaultLog FaultLog { get; set; }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.FaultLog.Add(FaultLog);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/FaultLogs/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.FaultLogs
{
    public class DeleteModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public DeleteModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        [BindProperty]
        public FaultLog FaultLog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FaultLog = await _context.FaultLog.FirstOrDefaultAsync(m => m.ID == id);

            if (FaultLog == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FaultLog = await _context.FaultLog.FindAsync(id);

            if (FaultLog != null)
            {
                _context.FaultLog.Remove(FaultLog);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/FaultLogs/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.FaultLogs
{
    public class DetailsModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public DetailsModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        public FaultLog FaultLog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FaultLog = await _context.FaultLog.FirstOrDefaultAsync(m => m.ID == id);

            if (FaultLog == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/FaultLogs/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.FaultLogs
{
    public class EditModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public EditModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        [BindProperty]
        public FaultLog FaultLog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FaultLog = await _context.FaultLog.FirstOrDefaultAsync(m => m.ID == id);

            if (FaultLog == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(FaultLog).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FaultLogExists(FaultLog.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool FaultLogExists(int id)
        {
            return _context.FaultLog.Any(e => e.ID == id);
        }
    }
}

Pages/FaultLogs/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MSV_LP.Data;
using MSV_LP.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MSV_LP.Pages.FaultLogs
{
    public class IndexModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public IndexModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        public IList<FaultLog> FaultLog { get;set; }
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        [BindProperty(SupportsGet = true)]
        public string LocomNo { get; set; }
        [BindProperty(SupportsGet = true)]
        public string dateNo { get; set; }

        public SelectList locoList { get; set; }
        public SelectList dateList { get; set; }

        public async Task OnGetAsync()
        {
            IQueryable<string> locoQuery = from m in _context.FaultLog
                                            orderby m.Locomotive
                                            select m.Locomotive;

            IQueryable<string> dateQuery = from n in _context.FaultLog
                                           orderby n.DownloadDate.ToString().Substring(0, 10)
                                           select n.DownloadDate.ToString().Substring(0,10);

            var Locos = from m in _context.FaultLog
                         select m;

            if (!string.IsNullOrEmpty(SearchString))
            {
                Locos = Locos.Where(s => s.Locomotive.Contains(SearchString));
            }

            if (!string.IsNullOrEmpty(dateNo))
            {
                Locos = Locos.Where(y => y.DownloadDate.ToString().Substring(0, 10) == dateNo);
            }

            if (!string.IsNullOrEmpty(LocomNo))
            {
                Locos = Locos.Where(x => x.Locomotive == LocomNo);
            }
            

            dateList = new SelectList(await dateQuery.Distinct().ToListAsync());
            locoList = new SelectList(await locoQuery.Distinct().ToListAsync());
            FaultLog = await Locos.ToListAsync();
        }
    }
}

Pages/FaultLogs/Upload.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using MSV_LP.Data;
using MSV_LP.Models;
using MSV_LP.Utilities;
using System.IO;
using System.Globalization;

namespace MSV_LP.Pages.FaultLogs
{
    public class UploadModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;
        //private readonly long _fileSizeLimit;
        private readonly string[] _permittedExtensions = { ".his" };

        public UploadModel(MSV_LP.Data.MSV_LPContext context, IConfiguration config)
        {
            _context = context;
            //_fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        [BindProperty]
        public BufferedSingleFileUploadDb FileUpload { get; set; }

        public string Result { get; private set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostUploadAsync()
        {
            // Perform an initial check to catch FileUpload class
            // attribute violations.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            var formFileContent = await FileHelpers.ProcessFormFile<BufferedSingleFileUploadDb>(FileUpload.FormFile, ModelState, _permittedExtensions);

            // Perform a second check to catch ProcessFormFile method
            // violations. If any validation check fails, return to the
            // page.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            // **WARNING!**
            // In the following example, the file is saved without
            // scanning the file's contents. In most production
            // scenarios, an anti-virus/anti-malware scanner API
            // is used on the file before making the file available
            // for download or for use by other systems. 
            // For more information, see the topic that accompanies 
            // this sample.

            //zpracovani souboru
            string result = System.Text.Encoding.UTF8.GetString(formFileContent);
            StringReader reader = new StringReader(result);
            string header = reader.ReadLine();
            string Locomotive = header.Substring(4, 7);
            string D_D = header.Substring(15, 8);
            string D_T = header.Substring(25, 8);
            string dateYear = D_D.Substring(0, 3);
            DateTime DownloadDate = DateTime.ParseExact(D_D, "yy-MM-dd", null);//log download date
            DateTime DownloadTime = DateTime.ParseExact(D_T, "HH:mm:ss", null);//
            float Odo = float.Parse(header.Substring(46, 9), CultureInfo.InvariantCulture.NumberFormat);


            /* creation of the FaultLog */
            var file = new FaultLog
            {
                Locomotive = Locomotive,
                DownloadDate = DownloadDate,
                DownloadTime = DownloadTime,
                Odometr = Odo
            };

            int firstFaultLine = 5; // number of lines to skip
            /* skip empty or unnecessary lines */
            for (int i = 1; i < firstFaultLine; i++)
            {
                reader.ReadLine();
            }

            /* creation of the Fault entry */
            while (reader.ReadLine() != null) //read till the end of file
            {
                string Entry = reader.ReadLine();
                string date = Entry.Substring(6, 5);
                string dateComplete = string.Concat(dateYear, date);
                var faultEntry = new Fault
                {
                    zkratka = Entry.Substring(0, 4),
                    datum = DateTime.ParseExact(dateComplete, "yy-MM-dd", null),
                    cas = Entry.Substring(13, 8),
                    trvani = Entry.Substring(24, 5),
                    zdrBit = Entry.Substring(30, 4),
                    rychlost = int.Parse(Entry.Substring(35, 3)),
                    PT = Entry.Substring(40, 4),
                    kontext = Entry.Substring(45, 4),
                    CisloPor = Entry.Substring(50, 4),
                    byte0 = ushort.Parse(Entry.Substring(55, 3)),
                    byte1 = ushort.Parse(Entry.Substring(59, 3)),
                    byte2 = ushort.Parse(Entry.Substring(63, 3)),
                    byte3 = ushort.Parse(Entry.Substring(67, 3)),
                    drahaH = int.Parse(Entry.Substring(71, 7))//,
                    //drahaL = int.Parse(Entry.Substring(79, 7))
                };
                _context.Fault.Add(faultEntry);
                await _context.SaveChangesAsync();
            }

            _context.FaultLog.Add(file);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }

    public class BufferedSingleFileUploadDb
    {
        [Required]
        [Display(Name = "File")]
        public IFormFile FormFile { get; set; }

        [Display(Name = "Note")]
        [StringLength(50, MinimumLength = 0)]
        public string Note { get; set; }
    }

}

Pages/Faults/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.Faults
{
    public class CreateModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public CreateModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Fault Fault { get; set; }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Fault.Add(Fault);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Faults/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.Faults
{
    public class DeleteModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public DeleteModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Fault Fault { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Fault = await _context.Fault.FirstOrDefaultAsync(m => m.ID == id);

            if (Fault == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Fault = await _context.Fault.FindAsync(id);

            if (Fault != null)
            {
                _context.Fault.Remove(Fault);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Faults/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MSV_LP.Data;
using MSV_LP.Models;

namespace MSV_LP.Pages.Faults
{
    public class DetailsModel : PageModel
    {
        private readonly MSV_LP.Data.MSV_LPContext _context;

        public DetailsModel(MSV_LP.Data.MSV_LPContext context)
        {
            _context = context;
        }

        public Fault Fault { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Fault = await _context.Fault.FirstOrDefaultAsync(m => m.ID == id);

            if (Fault == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/FaultLogs/Create.cshtml
@page
@model MSV_LP.Pages.FaultLogs.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FaultLog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FaultLog.Locomotive" class="control-label"></label>
                <input asp-for="FaultLog.Locomotive" class="form-control" />
                <span asp-validation-for="FaultLog.Locomotive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaultLog.DownloadDate" class="control-label"></label>
                <input asp-for="FaultLog.DownloadDate" class="form-control" />
                <span asp-validation-for="FaultLog.DownloadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/FaultLogs/Delete.cshtml
@page
@model MSV_LP.Pages.FaultLogs.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FaultLog</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FaultLog.Locomotive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FaultLog.Locomotive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FaultLog.DownloadDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FaultLog.DownloadDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="FaultLog.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/FaultLogs/Details.cshtml
@page
@model MSV_LP.Pages.FaultLogs.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FaultLog</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FaultLog.Locomotive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FaultLog.Locomotive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FaultLog.DownloadDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FaultLog.DownloadDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FaultLog.DownloadTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FaultLog.DownloadTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FaultLog.Odometr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FaultLog.Odometr)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.FaultLog.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/FaultLogs/Edit.cshtml
@page
@model MSV_LP.Pages.FaultLogs.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FaultLog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FaultLog.ID" />
            <div class="form-group">
                <label asp-for="FaultLog.Locomotive" class="control-label"></label>
                <input asp-for="FaultLog.Locomotive" class="form-control" />
                <span asp-validation-for="FaultLog.Locomotive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaultLog.DownloadDate" class="control-label"></label>
                <input asp-for="FaultLog.DownloadDate" class="form-control" />
                <span asp-validation-for="FaultLog.DownloadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/FaultLogs/Index.cshtml
@page
@model MSV_LP.Pages.FaultLogs.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Záznamy chybových logů</h1>

<p>
    <a class="button" asp-page="Upload">Nahrát log</a>
</p>

<form>
    <p>
        Hledej lokomotivu: <input type="text" asp-for="SearchString" />

        Dle čísla:
        <select asp-for="LocomNo" asp-items="Model.locoList">
            <option value="">Všechny</option>
        </select>

        Dle data:
        <select asp-for="dateNo" asp-items="Model.dateList">
            <option value="">Všechny</option>
        </select>

        <input type="submit" value="Filtruj" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FaultLog[0].ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaultLog[0].Locomotive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaultLog[0].DownloadDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaultLog[0].DownloadTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaultLog[0].Odometr)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.FaultLog) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Locomotive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DownloadDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DownloadTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Odometr)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Pages/FaultLogs/Upload.cshtml
@page
@model MSV_LP.Pages.FaultLogs.UploadModel

@{
    ViewData["Title"] = "Buffered Single File Upload (Db)";
}

<h1>Nahrajte chybový log .mhx</h1>

<form enctype="multipart/form-data" method="post">
    <dl>
        <dt>
            <label asp-for="FileUpload.FormFile"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.FormFile" type="file" />
            <span asp-validation-for="FileUpload.FormFile"></span>
        </dd>
    </dl>
    <input asp-page-handler="Upload" class="button" type="submit" value="Nahrát" />
</form>

<p class="result">
    @Model.Result
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}